### ISSUE TITLE
CfgRemoteExec.hpp - mode = 2 (should be mode = 1)

### ISSUE THREAD

**Issue by infiSTAR** [osuapoc/APOCAirdropAssistanceExile#6]
Hey
you changed the cfgRemoteExec to:

> class CfgRemoteExec
> {
>     class Functions
>     {
>         mode = 2;
>         jip = 0;
>         class fnc_AdminReq { allowedTargets=2; };
>         class ExileServer_system_network_dispatchIncomingMessage { allowedTargets=2; };
>         class APOC_srv_startAirdrop { allowedTargets=2;};
>     };
>     class Commands
>     {
>         mode=0;
>         jip=0;
>     };
> };

modes (https://community.bistudio.com/wiki/CfgRemoteExec):
0-turned off
1-turned on - taking whitelist into account
2-turned on - however, ignoring whitelists (default because of backward compatibility)

with other words, you don't need a white-list if you don't take them into count. With 2 you pretty much allow anything :)
Make it
mode = 1 please

**Comment by osuapoc** [comment]
Resolved via a6482cc.
